# Disable the Web Server.
# See https://docs.spring.io/spring-boot/docs/current/reference/html/howto-embedded-web-servers.html.
spring.main.web-application-type: none

# Additional server ports specified with Armeria configuration.
armeria:
  ports:
    - port: 3000
      protocols:
        - http
    - port: 8443
      protocols:
        - https
